source :rubygems
source "http://rubygems.org"

gem "growl_notify", "~> 0.0.1"
gem "guard", "~> 0.7.0"
gem "guard-rake", "~> 0.0.1"
gem "haml", "~> 3.1.3"
gem "jammit", "~> 0.6.3"
gem "jekyll", "~> 0.11.0"
gem "rb-fsevent", "~> 0.4.3.1"
gem "sass", "~> 3.1.7"